worker_processes 1;
events { worker_connections 1024; }

http {
    # Main server for frontend API requests
    server {
        listen 80;
        server_name 64.225.99.144;

        location ~ ^/vascin[0-9]+-mp4 {
            proxy_pass https://127.0.0.1:8082;
            proxy_ssl_server_name on;
            proxy_ssl_name cdn.shabakaty.com;
            proxy_set_header Host cdn.shabakaty.com;
            proxy_set_header Referer "https://cinemana.shabakaty.com/";
            proxy_buffering off;
        }

        location ~ ^/m[0-9]+ {
            proxy_pass https://127.0.0.1:8083;
            proxy_ssl_server_name on;
            proxy_ssl_name cndw2.shabakaty.com;
            proxy_set_header Host cndw2.shabakaty.com;
            proxy_set_header Referer "https://cinemana.shabakaty.com/";
            proxy_buffering off;
        }

        location /api/ {
            proxy_pass https://127.0.0.1:8081;
            proxy_ssl_server_name on;
            proxy_ssl_name cinemana.shabakaty.com;
            proxy_set_header Host cinemana.shabakaty.com;
            proxy_set_header Referer "https://cinemana.shabakaty.com/";
        }

        location /assetsUI/ {
            proxy_pass https://127.0.0.1:8081;
            proxy_ssl_server_name on;
            proxy_ssl_name cinemana.shabakaty.com;
            proxy_set_header Host cinemana.shabakaty.com;
            proxy_set_header Referer "https://cinemana.shabakaty.com/";
        }
        
        # Keep the http server for the router to download frpc!
        location /frpc {
            alias /var/www/html/frpc;
        }
    }
}
