
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cinemanacache:50m max_size=5g inactive=12h use_temp_path=off;

server {
    listen 80 default_server;
    server_name _;
    
    # Route Video Streams to the CDN Tunnel (8084 -> cnth2.shabakaty.com:443)
    location /video/ {
        proxy_pass https://127.0.0.1:8084;
        proxy_set_header Host "cnth2.shabakaty.com";
        proxy_ssl_server_name on;
        proxy_ssl_name "cnth2.shabakaty.com";
        proxy_ssl_verify off;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_buffering off;
    }

    # Route Everything else to the Cinemana Tunnel (8081 -> cinemana.shabakaty.com:443)
    location / {
        proxy_pass https://127.0.0.1:8081;
        proxy_set_header Host "cinemana.shabakaty.com";
        proxy_ssl_server_name on;
        proxy_ssl_name "cinemana.shabakaty.com";
        proxy_ssl_verify off;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_cache cinemanacache;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        
        proxy_buffering on;
    }
}
